import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import eren from "../../assets/avatars/eren.jpeg";
import mikasa from "../../assets/avatars/mikasa.jpeg";
import peter from "../../assets/avatars/peter.jpg";
import man3 from "../../assets/avatars/man3.png";
import woman2 from "../../assets/avatars/woman2.png";

export const dummyFollowers = [
  {
    _id: uuid(),
    firstName: "Eren",
    lastName: "Jaeger",
    username: "eren",
    password: "eren123",
    avatar: eren,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mikasa",
    lastName: "Ackerman",
    username: "mikasa",
    password: "mikasa123",
    avatar: mikasa,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Syeda",
    lastName: "Fatima",
    username: "fatima",
    password: "fatima123",
    avatar: woman2,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Peter",
    lastName: "Parker",
    username: "peter",
    password: "peter123",
    avatar: peter,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    username: "tony",
    password: "tony123",
    avatar: man3,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
