import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import male from "../../assets/avatars/male.png";
import { dummyBio, dummyLink, dummyDP } from "./dummyData";

/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Shahbaz",
    lastName: "Ahmad",
    username: "shahbazcse",
    password: "shahbaz123",
    avatar: dummyDP.shahbaz,
    about: dummyBio.shahbaz,
    portfolioURL: dummyLink.shahbaz,
    isVerified: false,
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Bruce",
    lastName: "Wayne",
    username: "bruce",
    password: "bruce123",
    avatar: dummyDP.bruce,
    about: dummyBio.bruce,
    portfolioURL: dummyLink.bruce,
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Eren",
    lastName: "Jaeger",
    username: "eren",
    password: "eren123",
    avatar: dummyDP.eren,
    about: dummyBio.eren,
    portfolioURL: dummyLink.eren,
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mikasa",
    lastName: "Ackerman",
    username: "mikasa",
    password: "mikasa123",
    avatar: dummyDP.mikasa,
    about: dummyBio.mikasa,
    portfolioURL: dummyLink.mikasa,
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Syeda",
    lastName: "Fatima",
    username: "fatima",
    password: "fatima123",
    avatar: dummyDP.syeda,
    about: dummyBio.syeda,
    portfolioURL: dummyLink.syeda,
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Peter",
    lastName: "Parker",
    username: "peter",
    password: "peter123",
    avatar: dummyDP.peter,
    about: dummyBio.peter,
    portfolioURL: dummyLink.peter,
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    username: "tony",
    password: "tony123",
    avatar: dummyDP.tony,
    about: dummyBio.tony,
    portfolioURL: dummyLink.tony,
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Steve",
    lastName: "Rogers",
    username: "steve",
    password: "steve123",
    avatar: dummyDP.steve,
    about: dummyBio.steve,
    portfolioURL: dummyLink.steve,
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mary",
    lastName: "Jane",
    username: "mary",
    password: "mary123",
    avatar: dummyDP.mary,
    about: dummyBio.mary,
    portfolioURL: dummyLink.mary,
    isVerified: true,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Gwen",
    lastName: "Stacy",
    username: "gwen",
    password: "gwen123",
    avatar: dummyDP.gwen,
    about: dummyBio.gwen,
    portfolioURL: dummyLink.gwen,
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "John",
    lastName: "Doe",
    username: "john",
    password: "john123",
    avatar: male,
    about: "This is a test profile",
    portfolioURL: "www.testprofile.com",
    isVerified: false,
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
