import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import shahbaz from "../../assets/avatars/shahbaz.jpg";
import batman from "../../assets/avatars/batman.png";
import male from "../../assets/avatars/male.png";
import boy1 from "../../assets/avatars/boy1.png";
import man1 from "../../assets/avatars/man1.png";
import man2 from "../../assets/avatars/man2.png";
import man3 from "../../assets/avatars/man3.png";
import woman2 from "../../assets/avatars/woman2.png";
import woman3 from "../../assets/avatars/woman3.png";
import woman4 from "../../assets/avatars/woman4.png";
import woman5 from "../../assets/avatars/woman5.png";

/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Shahbaz",
    lastName: "Ahmad",
    username: "shahbazcse",
    password: "shahbaz123",
    avatar: shahbaz,
    about: "",
    portfolioURL: "www.google.com",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Bruce",
    lastName: "Wayne",
    username: "bruce",
    password: "bruce123",
    avatar: batman,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Eren",
    lastName: "Jaeger",
    username: "eren",
    password: "eren123",
    avatar: boy1,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mikasa",
    lastName: "Ackerman",
    username: "mikasa",
    password: "mikasa123",
    avatar: woman3,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Syeda",
    lastName: "Fatima",
    username: "fatima",
    password: "fatima123",
    avatar: woman2,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Peter",
    lastName: "Parker",
    username: "peter",
    password: "peter123",
    avatar: man2,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    username: "tony",
    password: "tony123",
    avatar: man3,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Steve",
    lastName: "Rogers",
    username: "steve",
    password: "steve123",
    avatar: man1,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mary",
    lastName: "Jane",
    username: "mary",
    password: "mary123",
    avatar: woman4,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },

  {
    _id: uuid(),
    firstName: "Gwen",
    lastName: "Stacy",
    username: "gwen",
    password: "gwen123",
    avatar: woman5,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "John",
    lastName: "Doe",
    username: "john",
    password: "john123",
    avatar: male,
    about: "",
    portfolioURL: "",
    followers: [],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
