import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
import shahbaz from "../../assets/avatars/shahbaz.jpg";
import bruce from "../../assets/avatars/bruce.jpg";
import eren from "../../assets/avatars/eren.jpeg";
import mikasa from "../../assets/avatars/mikasa.jpeg";
import peter from "../../assets/avatars/peter.jpg";
import male from "../../assets/avatars/male.png";
import man1 from "../../assets/avatars/man1.png";
import man3 from "../../assets/avatars/man3.png";
import woman2 from "../../assets/avatars/woman2.png";
import woman4 from "../../assets/avatars/woman4.png";
import woman5 from "../../assets/avatars/woman5.png";
import { dummyFollowers } from "./dummyData";

/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Shahbaz",
    lastName: "Ahmad",
    username: "shahbazcse",
    password: "shahbaz123",
    avatar: shahbaz,
    about: "",
    portfolioURL: "www.google.com",
    isVerified: false,
    followers: [...dummyFollowers],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Bruce",
    lastName: "Wayne",
    username: "bruce",
    password: "bruce123",
    avatar: bruce,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [...dummyFollowers.slice(0, 2).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Eren",
    lastName: "Jaeger",
    username: "eren",
    password: "eren123",
    avatar: eren,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [...dummyFollowers.slice(0, 4).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mikasa",
    lastName: "Ackerman",
    username: "mikasa",
    password: "mikasa123",
    avatar: mikasa,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [...dummyFollowers.slice(0, 3).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Syeda",
    lastName: "Fatima",
    username: "fatima",
    password: "fatima123",
    avatar: woman2,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [...dummyFollowers.slice(0, 4).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Peter",
    lastName: "Parker",
    username: "peter",
    password: "peter123",
    avatar: peter,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [...dummyFollowers.slice(0, 3).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Tony",
    lastName: "Stark",
    username: "tony",
    password: "tony123",
    avatar: man3,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [...dummyFollowers.slice(0, 4).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Steve",
    lastName: "Rogers",
    username: "steve",
    password: "steve123",
    avatar: man1,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [...dummyFollowers.slice(0, 2).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mary",
    lastName: "Jane",
    username: "mary",
    password: "mary123",
    avatar: woman4,
    about: "",
    portfolioURL: "",
    isVerified: true,
    followers: [...dummyFollowers.slice(0, 3).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Gwen",
    lastName: "Stacy",
    username: "gwen",
    password: "gwen123",
    avatar: woman5,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [...dummyFollowers.slice(0, 2).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "John",
    lastName: "Doe",
    username: "john",
    password: "john123",
    avatar: male,
    about: "",
    portfolioURL: "",
    isVerified: false,
    followers: [...dummyFollowers.slice(0, 1).map((p) => p)],
    following: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
